PHP 8 Support
serbanghita/Mobile-Detect pull request #848
Opened 2020-10-23 09:01 UTC by adlenton

Hey,

I took the liberty to propose a minimal changeset for php 8 support and with that also drop support for unsupported php versions (https://www.php.net/supported-versions.php).

- dropped support for php versions older than 7.2
- updated phpunit version
- compatibility fixes

2020-12-16 13:31 UTC, brainexe commented
@serbanghita I'm also waiting for this PR, as it's blocking us from a full PHP8 upgrade :)

2021-01-26 09:53 UTC, serbanghita commented
@adlenton Thank you, I actually needed this! I'm review-ing it and this will be the basis of `3.0.0`

2021-01-26 09:58 UTC, serbanghita requested changes

2021-01-26 09:58 UTC, serbanghita commented on tests/BasicsTest.php
> -    public function testSetDetectionType()
Why was this removed? At the moment, just looking at the code I don't remember the actual functionality and purpose.

2021-01-26 09:58 UTC, serbanghita commented on .travis.yml
> +    - php: 7.4
We migrated to GH Actions yesterday, check https://github.com/serbanghita/Mobile-Detect/blob/master/.github/workflows/devel.yml
Can you include PHP 8 as well in the matrix?

2021-01-26 09:58 UTC, serbanghita commented on .travis.yml
>      - php: nightly
Do we want to test for edge?
I'd be more conservative (like the whole script) and put explicit versions.

2021-01-26 09:59 UTC, serbanghita commented
@bogdananton can you look into this PR as well?

2021-01-26 10:09 UTC, serbanghita commented
@brainexe I will move as fast as I can. There is also this PR that I have to account for https://github.com/serbanghita/Mobile-Detect/pull/823
Can you also review the current PR changes?

2021-11-01 22:38 UTC, dereuromark commented
Is there any update on this?

We have tons of those

> `PHP Deprecated:  preg_match(): Passing null to parameter #2 ($subject) of type string is deprecated in /home/runner/work/.../vendor/mobiledetect/mobiledetectlib/Mobile_Detect.php on line 1460`

in our CI system now for PHP 8.1+ etc.

2022-11-09 17:20 UTC, serbanghita commented
I have opened a PR for support of PHP7 https://github.com/serbanghita/Mobile-Detect/pull/900

This PR contains shallow changes and I cannot continue with it in this state.
If any of you guys want to be a reviewer on https://github.com/serbanghita/Mobile-Detect/pull/900 - let me know

2022-11-09 17:20 UTC, closed without merging